# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20151218_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
